services:
  postgres:
    image: postgres:12.22
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data
    volumes:
      - votes_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres_db

  pgadmin4:
    image: elestio/pgadmin:REL-8_13
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - '8080:8080'
    volumes:
      - votes_pgadmin:/pgadmin4/servers.json
    networks:
      - postgres_db 

volumes:
  votes_postgres:
  votes_pgadmin:

networks:
  postgres_db:
    driver: bridge